defaults: &defaults
  access_key_id: ACCESS_KEY
  secret_access_key: SECRET_KEY

  # http://docs.amazonwebservices.com/AmazonS3/latest/dev/index.html?RESTAccessPolicy.html#RESTCannedAccessPolicies
  s3_permissions: :public_read
  # set to HTTPS when read permissions are more restrictive
  s3_protocol: http

development:
  <<: *defaults
  bucket: teambox_dev_assets

test:
  <<: *defaults
  bucket: teambox_test_assets

production:
  <<: *defaults
  bucket: teambox_assets
