development:
  adapter: mysql
  server: localhost
  username: root 
  password:
  database: teambox2
  
test: &TEST
  adapter: mysql
  server: localhost
  username: root 
  password:
  database: teambox2_test

production:
  adapter: mysql
  server: localhost
  username: root 
  password:
  database: teambox2_production

cucumber: &CUCUMBER
  <<: *TEST
culerity_development:
  <<: *CUCUMBER
culerity_continuousintegration:
  <<: *CUCUMBER